@echo off
chcp 65001 >nul
echo 正在执行清洁构建流程...
echo 1. 终止残留进程...
taskkill /f /im "猫步互联 Pro.exe" 2>nul
taskkill /f /im "electron.exe" 2>nul
echo 2. 清理旧打包产物...
if exist release rmdir /s /q release
echo 3. 开始执行打包构建...
call npx electron-builder --win --x64
echo 打包完成！
pause
